<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="box_width" value="0.102" />
  <xacro:property name="disk_diameter" value="0.05" />
  <xacro:property name="disk_thickness" value="0.01" />
  <xacro:property name="dial_thickness" value="0.002" />

  <xacro:macro name="joint_model" params="prefix">

    <!-- Materials -->
    <material name="${prefix}black">
      <color rgba="0 0 0 1"/>
    </material>
    <material name="${prefix}white">
      <color rgba="1 1 1 1"/>
    </material>
    <material name="${prefix}red">
      <color rgba="1 0 0 1"/>
    </material>

    <link name="${prefix}base_link"/>

    <joint name="${prefix}stator_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}stator_link"/>
      <origin xyz="0 0 ${box_width/2}"/>
    </joint>

    <link name="${prefix}stator_link">
      <visual>
        <geometry>
          <box size="${box_width} ${box_width} ${box_width}"/>
        </geometry>
        <material name="${prefix}black"/>
      </visual>
    </link>

    <joint name="${prefix}motor_joint" type="revolute">
      <parent link="${prefix}stator_link"/>
      <child link="${prefix}rotor_link"/>
      <origin xyz="0 0 ${box_width/2}"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="${prefix}rotor_link">
      <visual>
        <geometry>
          <cylinder length="${disk_thickness}" radius="${disk_diameter/2}"/>
        </geometry>
        <material name="${prefix}red"/>
      </visual>
    </link>

    <joint name="${prefix}indicator" type="fixed">
      <parent link="${prefix}rotor_link"/>
      <child link="${prefix}angle_link"/>
      <origin xyz="${disk_diameter/4} 0 ${disk_thickness/2}"/>
    </joint>

    <link name="${prefix}angle_link">
      <visual>
        <geometry>
          <box size="${disk_diameter/2} ${dial_thickness} ${dial_thickness}"/>
        </geometry>
        <material name="${prefix}white"/>
      </visual>
    </link>
  </xacro:macro>
</robot>